//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgingTotes
    {
        public int ID { get; set; }
        public string ToteNumber { get; set; }
        public Nullable<int> OrdersinTote { get; set; }
    }
}
