//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_exceptions
    {
        public string usr_id { get; set; }
        public string exception_type { get; set; }
        public string item_id { get; set; }
        public Nullable<int> Units { get; set; }
    }
}
